### ISSUE TITLE
no virtual method styleUrl when using initMapbox

### ISSUE THREAD

**Issue by ehud166** [dji-sdk/Mobile-UXSDK-Android#122]
hey i`m using the latest dji sdk version and the latest  mapbox plugin,
it`s seems that mapbox doesn`t use any more this method but dji still initialize with this so the app crashed

the exception down below:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dji.ux.sample, PID: 19116
    java.lang.NoSuchMethodError: No virtual method styleUrl(Ljava/lang/String;)Lcom/mapbox/mapboxsdk/maps/MapboxMapOptions; in class Lcom/mapbox/mapboxsdk/maps/MapboxMapOptions; or its super classes (declaration of 'com.mapbox.mapboxsdk.maps.MapboxMapOptions' appears in /data/app/~~_TLs319y_-Bkc2JxeW1BUQ==/com.dji.ux.sample-O5TTwe-8tc52UprtNI3VcA==/base.apk!classes3.dex)
        at com.dji.mapkit.mapbox.provider.MapboxProvider.requestMapView(Unknown Source:42)
        at com.dji.mapkit.core.providers.MapProvider.dispatchMapViewRequest(Unknown Source:11)
        at dji.ux.widget.MapWidget.initMapboxMap(Unknown Source:29)
        at com.dji.ux.sample.CompleteWidgetActivity.onCreate(CompleteWidgetActivity.java:124)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/DJICrashHandler: uncaughtException 3
E/UsbAccessoryService: final destroy() 71
E/UsbAccessoryService: final destroy() 72
E/wm220: ****resetSwitchFromWifiFlag
E/DJIUsbAccessoryReceiver: receiver destroySession
E/UsbAccessoryService: final destroy() 73
E/UsbAccessoryService: final destroy() 75
    final destroy() 76

thx

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/46948'>Zendesk ticket #46948</a>:<br><br>Dear Client
Thank you for contacting DJI.

It is suggested that you using Google Map or AMap rather than Mapbox, as far as I know we won't continue supporting Mapbox.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support<br><p><em><small>added by Git-Zen</small></em></p>

**Comment by ehud166** [comment]
> Agent comment from William Wong in [Zendesk ticket #46948](https://djisdksupport.zendesk.com/agent/tickets/46948):
> 
> Dear Client
> Thank you for contacting DJI.
> 
> It is suggested that you using Google Map or AMap rather than Mapbox, as far as I know we won't continue supporting Mapbox.
> 
> Hopefully our solution can help you.
> Kindly Regards,
> DJI Developer Support
> 
> _added by Git-Zen_


thanks for your answer!!

i have to use mapbox API for offline mode,
my app should present the map without internet
