### ISSUE TITLE
Crash when clicked on Ok for Flyzone warning. (M300)

### ISSUE THREAD

**Issue by mayurpatil307** [dji-sdk/Mobile-UXSDK-Android#131]
The app crashes when we click on OK when the Flyzone/altitude Warning Dialog is received.
eg. you are in an altitude zone and your flight altitude is restricted to 120m

We are able to replicate this only on M300.

Can you please help in resolving the issue.

Crash Logs:
--------- beginning of crash
06-23 15:47:14.224  2381  2381 E AndroidRuntime: FATAL EXCEPTION: main
06-23 15:47:14.224  2381  2381 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@6896404 is not valid; is your activity running?
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.view.ViewRootImpl.setView(ViewRootImpl.java:681)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.widget.Toast$TN.handleShow(Toast.java:459)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:167)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6240)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1000)
06-23 15:47:14.224  2381  2381 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/49454'>Zendesk ticket #49454</a>:<br><br>Dear Client
Thank you for contacting DJI.

We will test locally soon.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/49454'>Zendesk ticket #49454</a>:<br><br>Dear Client
Thank you for contacting DJI.

I am sorry that UXSDK project has been suspend, therefore no workforces to fix this issue. We recommand you switch to UXSDK BETA proeject which is an open-source project.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
