### ISSUE TITLE
Exception thrown on Scheduler.Worker thread.Add'onError' handling.

### ISSUE THREAD

**Issue by Likeshadows** [dji-sdk/Mobile-UXSDK-Android#61]
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: dji.thirdparty.rx.exceptions.OnErrorNotImplementedException
	at dji.thirdparty.rx.Observable$26.onError(Observable.java:8524)
	at dji.thirdparty.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at dji.thirdparty.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at dji.thirdparty.rx.observers.SerializedObserver.onError(SerializedObserver.java:158)
	at dji.thirdparty.rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerError(OnSubscribeConcatMap.java:192)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onError(OnSubscribeConcatMap.java:340)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8748)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
	at java.util.HashMap$EntryIterator.next(HashMap.java:891)
	at java.util.HashMap$EntryIterator.next(HashMap.java:890)
	at dji.ux.widget.VisionWidget.getOverallVisionSystemStatus(Unknown Source)
	at dji.ux.widget.VisionWidget.getAvoidanceSystemStatus(Unknown Source)
	at dji.ux.widget.VisionWidget.updateWidget(Unknown Source)
	at dji.ux.base.FrameLayoutWidget$2.a(Unknown Source)
	at dji.ux.base.FrameLayoutWidget$2.call(Unknown Source)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	... 9 more
dji.thirdparty.rx.exceptions.OnErrorNotImplementedException
	at dji.thirdparty.rx.Observable$26.onError(Observable.java:8524)
	at dji.thirdparty.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at dji.thirdparty.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at dji.thirdparty.rx.observers.SerializedObserver.onError(SerializedObserver.java:158)
	at dji.thirdparty.rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerError(OnSubscribeConcatMap.java:192)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onError(OnSubscribeConcatMap.java:340)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8748)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
	at java.util.HashMap$EntryIterator.next(HashMap.java:891)
	at java.util.HashMap$EntryIterator.next(HashMap.java:890)
	at dji.ux.widget.VisionWidget.getOverallVisionSystemStatus(Unknown Source)
	at dji.ux.widget.VisionWidget.getAvoidanceSystemStatus(Unknown Source)
	at dji.ux.widget.VisionWidget.updateWidget(Unknown Source)
	at dji.ux.base.FrameLayoutWidget$2.a(Unknown Source)
	at dji.ux.base.FrameLayoutWidget$2.call(Unknown Source)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	... 9 more
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
	at java.util.HashMap$EntryIterator.next(HashMap.java:891)
	at java.util.HashMap$EntryIterator.next(HashMap.java:890)
	at dji.ux.widget.VisionWidget.getOverallVisionSystemStatus(Unknown Source)
	at dji.ux.widget.VisionWidget.getAvoidanceSystemStatus(Unknown Source)
	at dji.ux.widget.VisionWidget.updateWidget(Unknown Source)
	at dji.ux.base.FrameLayoutWidget$2.a(Unknown Source)
	at dji.ux.base.FrameLayoutWidget$2.call(Unknown Source)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/29113'>Zendesk ticket #29113</a>:<br><br>Thanks for reporting on this issue - I'm consulting with out engineers and will update you as soon as possible.

Lisa Fedane
DJI Developer Support

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/29113'>Zendesk ticket #29113</a>:<br><br>Can you provide the following info:

1. Drone/Device you're connecting the SDK app too:
2. Drone/Device firmware version:
3. Mobile Device with OS version:
4. List the steps to reproduce the error:

Lisa Fedane
DJI Developer Support

**Comment by india2sarthak** [comment]
Facing the same issue. Any update on this?
