### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.setFirmwareStoreDirectory

### ISSUE THREAD

**Issue by chinobot-zj** [dji-sdk/Mobile-UXSDK-Android#62]
ux sdk 4.11.1
三星 S6
所有权限申请好了
第一次不会崩溃，杀掉app后重启之后报如下错：

java.lang.UnsatisfiedLinkError: No implementation found for void dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.setFirmwareStoreDirectory(java.lang.String) (tried Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory and Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory__Ljava_lang_String_2)
        at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.setFirmwareStoreDirectory(Native Method)
        at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.e()
        at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.b()
        at dji.upgrade.internal.csdk.CSDKManager.a()
        at dji.upgrade.internal.UpgradeManagerImpl.a()
        at dji.sdk.sdkmanager.DJISDKManager.initParams()
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager()
        at dji.sdk.sdkmanager.DJISDKManager.registerApp()
        at dji.sdk.sdkmanager.DJISDKManager.access$600()
        at dji.sdk.sdkmanager.DJISDKManager$5$1.onDownloadSuccess()
        at dji.internal.flysafe.DJIFlySafeDBLoader.a()
        at dji.sdk.sdkmanager.DJISDKManager$5.run()
        at dji.sdksharedlib.util.DJISDKCacheThreadManager$1.run()
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)

**Comment by The1only** [comment]
What was the solution, I got the same error.

**Comment by Asendo316** [comment]
Have you been able to resolve this please?

**Comment by wangtran** [comment]
I got the same issue. Why was it closed? No solution?
